name: Sample-book-app

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: ... buil success ...
        run: echo Building of node application is starting ..

      - name: ... check node version ...
        run: node -v 

      - name: ... check node version ...
        run: | 
          npm install
          sudo npm install -g pm2
          pm2 start -n "My task name" index.js
          pm2 list
        
  deploy-dev:
    name: Deploy DEV
    runs-on: ubuntu-latest
    needs: [build]

    steps:
      - name: ... deploy success ...
        run: pm2 list   

  tests-dev:
    name: Tests DEV
    runs-on: ubuntu-latest
    needs: [deploy-dev]

    steps:
      - name: ... tests success ...
        run: echo Testing on DEV has started ..

  deploy-stg:
    name: Deploy STG
    runs-on: ubuntu-latest
    needs: [tests-dev]

    steps:
      - name: ... deploy success ...
        run: echo Deplyment to STG has started ..   

  tests-stg:
    name: Tests STG
    runs-on: ubuntu-latest
    needs: [deploy-stg]

    steps:
      - name: ... tests success ...
        run: echo Testing on STG has started ..

  deploy-prd:
    name: Deploy PRD
    runs-on: ubuntu-latest
    needs: [tests-stg]

    steps:
      - name: ... deploy success ...
        run: echo Deplyment to PRD has started ..   

  tests-prd:
    name: Tests PRD
    runs-on: ubuntu-latest
    needs: [deploy-prd]

    steps:
      - name: ... tests success ...
        run: echo Testing on PRD has started ..


